### ISSUE TITLE
Testing collectd in collectd/ci:el6_x86_64 container fails

### ISSUE THREAD

**Issue by p-zak** [collectd/ci-docker#15]
Testing collectd in collectd/ci:el6_x86_64 container fails since this change: https://github.com/collectd/ci-docker/commit/498f3284632af166eeb7940156da36e9ce5c78bc with error:
```
/checks/check-built-plugins.sh
/checks/check-built-plugins.sh: line 14: conditional binary operator expected
```

It fails for many PRs (example: https://github.com/collectd/collectd/pull/3772, more details: https://github.com/collectd/collectd/pull/3772/checks?check_run_id=1359405872)

It seems that `if [[ -v want["${p}"] ]];` added here: https://github.com/collectd/ci-docker/commit/498f3284632af166eeb7940156da36e9ce5c78bc#diff-0daf298549f7a79a0087786c21760e0cc5f561fdd675e81e50b7283ec3a009f9R14 will work only for `bash` >= 4.3 (as stated here: 
http://git.savannah.gnu.org/cgit/bash.git/tree/CHANGES#n1889)

It seems that EL6 contains `bash` 4.1 in which `[[ -v ]]` option doesn't understand array references.

**Comment by mrunge** [comment]
It looks like this is addressed by https://github.com/collectd/collectd/pull/3784

**Comment by elfiesmelfie** [comment]
Because the distro is unsupported, the action required here is most likely: delete the branch

It depends on the container build automation being revived, since travis no longer runs (see: https://github.com/collectd/ci-docker/issues/16)
