### ISSUE TITLE
Containers are not being built and published

### ISSUE THREAD

**Issue by elfiesmelfie** [collectd/ci-docker#16]
The containers are not currently being built/published. Travis CI is supposed to publish the containers, however, it has been disabled. In collectd/collectd, it was removed from the CI altogether.

Perhaps github actions or should be considered for building/publishing the containers instead, so there can continue to be common containers for testing, which can be updated to more modern distros.

**Comment by elfiesmelfie** [comment]
I would like to propose the following CI actions:

- [] Periodically build all the containers, and push to dockerhub (https://github.com/collectd/ci-docker/pull/17)
- [] On a PR to various distro branches, build the container, (but don't push), to ensure they work (https://github.com/collectd/ci-docker/pull/19)
- [] On merge to a distro branch, the container should be rebuilt and pushed to dockerhub.

**Comment by octo** [comment]
I believe that this how the GitHub Actions have been set up. The last point was recently fixed.
